import type { VercelRequest,VercelResponse } from '@vercel/node'
import { audit,requireAdmin } from './_lib'
const req=(r:VercelRequest)=>{const h=new Headers();for(const[k,v]of Object.entries(r.headers)){if(typeof v==='string')h.set(k,v);else if(Array.isArray(v))h.set(k,v.join(','))}return new Request(`https://${r.headers.host||'localhost'}${r.url||'/api/admin/actions'}`,{method:r.method,headers:h,body:JSON.stringify(r.body||{})})}
export default async function handler(r:VercelRequest,res:VercelResponse){if(r.method!=='POST')return res.status(405).json({error:'Method not allowed'});const c=await requireAdmin(req(r));if('error'in c){const x=c.error;return res.status(x.status).send(await x.json())}const{admin,user,role}=c,b=r.body||{},action=String(b.action||''),shopId=String(b.shopId||'');try{
if(['approve_payment','reject_payment','suspend','reactivate','extend_trial','end_trial','toggle_card','delete_card','update_card','create_card'].includes(action)){const q=await admin.from('shops').select('*').eq('id',shopId).maybeSingle();if(q.error||!q.data)return res.status(404).json({error:'Shop not found'});const shop=q.data,prev={account_status:shop.account_status,plan:shop.plan,subscription_status:shop.subscription_status,payment_status:shop.payment_status,payment_verification_status:shop.payment_verification_status,product_limit:shop.product_limit,is_active:shop.is_active,storefront_published:shop.storefront_published,page_config:shop.page_config};let u:any={updated_at:new Date().toISOString()},message='Updated.';
if(action==='approve_payment'){if(shop.payment_verification_status!=='pending'&&shop.payment_status!=='pending')return res.status(409).json({error:'This payment is not pending verification.'});const now=new Date().toISOString();u={...u,account_status:'active',plan:'pro',premium_status:'active',product_limit:null,payment_required:false,payment_status:'paid',payment_verification_status:'approved',payment_verified_at:now,payment_verified_by:user.id,paid_at:now,is_active:true,storefront_published:true,published_at:now,subscription_status:'active'};const pp=await admin.from('shop_payments').select('id').eq('shop_id',shopId).eq('status','pending').order('created_at',{ascending:false}).limit(1).maybeSingle();if(pp.data)await admin.from('shop_payments').update({status:'paid',paid_at:now}).eq('id',pp.data.id);const sub=await admin.from('subscriptions').select('id').eq('shop_id',shopId).maybeSingle();if(sub.data)await admin.from('subscriptions').update({status:'active',plan:'premium',amount:9,currency:'USD',billing_cycle:'none',subscription_started_at:now,current_period_start:now,current_period_end:null,updated_at:now}).eq('id',sub.data.id);await admin.from('payment_events').insert({shop_id:shopId,owner_id:shop.owner_id,provider:'nardopay',event_type:'manual_admin_approval',amount:9,currency:'USD',payload:{payment_reference:shop.payment_reference,approved_by:user.id,approved_at:now},processed:true,processed_at:now});message='Payment approved. '+shop.name+' is now Pro.'}
if(action==='reject_payment'){u={...u,account_status:'free',plan:'free',premium_status:'inactive',product_limit:3,payment_required:true,payment_status:'unpaid',payment_verification_status:'rejected'};message='Payment rejected. The shop remains unpaid.'}
if(action==='suspend')u={...u,is_active:false,account_status:'suspended'},message='Shop suspended.'
if(action==='reactivate')u={...u,is_active:true,account_status:['pro','premium'].includes(shop.plan)?'active':'free'},message='Shop reactivated.'
if(action==='extend_trial'){const d=Math.max(1,Math.min(90,Number(b.days||3))),base=shop.trial_ends_at&&new Date(shop.trial_ends_at)>new Date()?new Date(shop.trial_ends_at):new Date();base.setDate(base.getDate()+d);u={...u,subscription_status:'trial',trial_ends_at:base.toISOString(),trial_started_at:shop.trial_started_at||new Date().toISOString(),product_limit:3,payment_required:false};message='Trial extended by '+d+' days.'}
if(action==='end_trial')u={...u,subscription_status:'expired',trial_ends_at:new Date().toISOString(),product_limit:3,payment_required:true,payment_status:'unpaid'},message='Trial ended.'
if(['toggle_card','delete_card','update_card','create_card'].includes(action)){const cfg=shop.page_config&&typeof shop.page_config==='object'?shop.page_config:{},cards=Array.isArray(cfg.why_shop_cards)?[...cfg.why_shop_cards]:[],id=String(b.cardId||'');if(action==='create_card'){const custom=cards.filter((x:any)=>x.id!=='location'),limit=['pro','premium'].includes(shop.plan)?6:1;if(custom.length>=limit)return res.status(409).json({error:'Custom card limit reached.'});cards.push({id:'card-'+Date.now(),icon:String(b.icon||'Star'),title:String(b.title||''),description:String(b.description||'')});message='Custom card created.'}else{if(id==='location')return res.status(400).json({error:'The default Location card cannot be changed or deleted.'});const i=cards.findIndex((x:any)=>x.id===id);if(i<0)return res.status(404).json({error:'Card not found'});if(action==='toggle_card')cards[i]={...cards[i],disabled:Boolean(b.disabled)};if(action==='delete_card')cards.splice(i,1);if(action==='update_card')cards[i]={...cards[i],icon:b.icon||cards[i].icon,title:b.title||cards[i].title,description:b.description||cards[i].description};message=action==='delete_card'?'Custom card deleted.':'Custom card updated.'}u={...u,page_config:{...cfg,why_shop_cards:cards}}}
const saved=await admin.from('shops').update(u).eq('id',shopId);if(saved.error)throw saved.error;await audit({admin,userId:user.id,role,action:'shop.'+action,targetType:'shop',targetId:shopId,previousState:prev,newState:u,reason:b.reason});return res.json({success:true,message})}
if(action==='create_promo'){const code=String(b.code||'').trim().toUpperCase();if(!/^[A-Z0-9_-]{3,32}$/.test(code))return res.status(400).json({error:'Invalid promo code.'});const x=await admin.from('promo_codes').insert({code,description:String(b.description||''),trial_days:Math.max(1,Math.min(90,Number(b.trial_days||30))),max_redemptions:Math.max(1,Number(b.max_redemptions||20)),active:true}).select().single();if(x.error)throw x.error;await audit({admin,userId:user.id,role,action:'promo.create',targetType:'promo_code',targetId:x.data.id,newState:x.data});return res.json({success:true})}
if(action==='toggle_promo'){const id=String(b.promoId||'');const x=await admin.from('promo_codes').update({active:Boolean(b.active),updated_at:new Date().toISOString()}).eq('id',id);if(x.error)throw x.error;await audit({admin,userId:user.id,role,action:'promo.toggle',targetType:'promo_code',targetId:id,newState:{active:Boolean(b.active)}});return res.json({success:true})}
return res.status(400).json({error:'Unknown admin action'})}catch(e){return res.status(500).json({error:e instanceof Error?e.message:'Admin action failed'})}}
