import type { VercelRequest,VercelResponse } from '@vercel/node'
import { requireAdmin } from './_lib'
const req=(r:VercelRequest)=>{const h=new Headers();for(const[k,v]of Object.entries(r.headers)){if(typeof v==='string')h.set(k,v);else if(Array.isArray(v))h.set(k,v.join(','))}return new Request(`https://${r.headers.host||'localhost'}${r.url||'/api/admin/data'}`,{method:'GET',headers:h})}
async function emails(admin:any,ids:string[]){const m=new Map<string,string>();await Promise.all([...new Set(ids.filter(Boolean))].map(async id=>{const r=await admin.auth.admin.getUserById(id);if(r.data.user)m.set(id,r.data.user.email||'')}));return m}
async function shops(admin:any){const r=await admin.from('shops').select('*').eq('page_type','clothing').order('created_at',{ascending:false});if(r.error)throw r.error;const ps=await admin.from('profiles').select('id,full_name,updated_at');if(ps.error)throw ps.error;const pm=new Map((ps.data||[]).map((x:any)=>[x.id,x]));const em=await emails(admin,(r.data||[]).map((x:any)=>x.owner_id));const out=[];for(const s of r.data||[]){const c=await admin.from('products').select('id',{count:'exact',head:true}).eq('shop_id',s.id);out.push({...s,owner_name:pm.get(s.owner_id)?.full_name||'',owner_email:em.get(s.owner_id)||'',product_count:c.count||0})}return out}
export default async function handler(r:VercelRequest,res:VercelResponse){if(r.method!=='GET')return res.status(405).json({error:'Method not allowed'});const ctx=await requireAdmin(req(r));if('error'in ctx){const x=ctx.error;return res.status(x.status).send(await x.json())}try{const s=new URL(r.url||'',`https://${r.headers.host||'localhost'}`).searchParams.get('section')||'overview',a=ctx.admin;
if(s==='overview'){const[ss,p,l]=await Promise.all([shops(a),a.from('products').select('id',{count:'exact',head:true}),a.from('admin_audit_logs').select('*').order('created_at',{ascending:false}).limit(12)]);const now=Date.now(),tr=ss.filter((x:any)=>x.subscription_status==='trial'&&x.trial_ends_at),pending=ss.filter((x:any)=>x.payment_verification_status==='pending'||x.payment_status==='pending');return res.json({metrics:{totalShops:ss.length,activeShops:ss.filter((x:any)=>x.is_active).length,pendingPayments:pending.length,activeTrials:tr.filter((x:any)=>new Date(x.trial_ends_at).getTime()>now).length,proShops:ss.filter((x:any)=>['pro','premium'].includes(x.plan)).length,expiredTrials:tr.filter((x:any)=>new Date(x.trial_ends_at).getTime()<=now).length,totalProducts:p.count||0,totalVisitors:ss.reduce((n:number,x:any)=>n+Number(x.lifetime_unique_visits||0),0)},pending:pending.slice(0,10),activity:l.data||[]})}
if(s==='shops'){let ss=await shops(a),f=new URL(r.url||'',`https://${r.headers.host||'localhost'}`).searchParams.get('filter')||'all';const now=new Date();ss=ss.filter((x:any)=>f==='all'||f==='active'&&x.is_active||f==='trial'&&x.subscription_status==='trial'&&x.trial_ends_at&&new Date(x.trial_ends_at)>now||f==='pending_payment'&&(x.payment_verification_status==='pending'||x.payment_status==='pending')||f==='pro'&&['pro','premium'].includes(x.plan)||f==='expired'&&(x.subscription_status==='expired'||x.trial_ends_at&&new Date(x.trial_ends_at)<=now)||f==='suspended'&&(x.account_status==='suspended'||!x.is_active));return res.json({shops:ss})}
if(s==='payments'){const ss=await shops(a),f=new URL(r.url||'',`https://${r.headers.host||'localhost'}`).searchParams.get('status')||'pending',payments=ss.map((x:any)=>({id:x.id,shop_id:x.id,shop_name:x.name,slug:x.slug,owner_email:x.owner_email,amount:x.payment_amount||9,currency:x.payment_currency||'USD',reference:x.payment_reference,submitted_at:x.payment_submitted_at,created_at:x.created_at,status:x.payment_verification_status==='pending'||x.payment_status==='pending'?'pending':x.payment_verification_status==='approved'||x.payment_status==='paid'?'approved':x.payment_verification_status==='rejected'?'rejected':'unpaid'})).filter((x:any)=>f==='all'||x.status===f);return res.json({payments})}
if(s==='subscriptions'){const r1=await a.from('subscriptions').select('*').order('created_at',{ascending:false});if(r1.error)throw r1.error;const ss=await shops(a),m=new Map(ss.map((x:any)=>[x.id,x]));return res.json({subscriptions:(r1.data||[]).map((x:any)=>({...x,shop_name:m.get(x.shop_id)?.name||'—',owner_email:m.get(x.shop_id)?.owner_email||''}))})}
if(s==='trials'){const ss=await shops(a),now=Date.now();return res.json({trials:ss.filter((x:any)=>x.subscription_status==='trial'&&x.trial_ends_at).map((x:any)=>{const e=new Date(x.trial_ends_at).getTime();return{...x,type:x.plan==='pro'||x.plan==='premium'?'Promo Pro':'Standard',status:e<=now?'expired':e-now<=172800000?'expiring_soon':'active'}})})}
if(s==='promos'){const[p,rr]=await Promise.all([a.from('promo_codes').select('*').order('created_at',{ascending:false}),a.from('promo_redemptions').select('*').order('redeemed_at',{ascending:false})]);if(p.error)throw p.error;if(rr.error)throw rr.error;const ss=await shops(a),pm=await a.from('profiles').select('id,full_name');const em=await emails(a,(rr.data||[]).map((x:any)=>x.profile_id)),sm=new Map(ss.map((x:any)=>[x.id,x])),pr=new Map((p.data||[]).map((x:any)=>[x.id,x])),um=new Map((pm.data||[]).map((x:any)=>[x.id,x]));return res.json({promos:p.data||[],redemptions:(rr.data||[]).map((x:any)=>({...x,code:pr.get(x.promo_code_id)?.code||'—',shop_name:sm.get(x.shop_id)?.name||'—',user_name:um.get(x.profile_id)?.full_name||'',user_email:em.get(x.profile_id)||''}))})}
if(s==='products'){const p=await a.from('products').select('*').order('created_at',{ascending:false}).limit(500);if(p.error)throw p.error;const ss=await shops(a),m=new Map(ss.map((x:any)=>[x.id,x.name]));return res.json({products:(p.data||[]).map((x:any)=>({...x,shop_name:m.get(x.shop_id)||'—'}))})}
if(s==='why_cards'){const ss=await shops(a);return res.json({shops:ss.map((x:any)=>{const cards=Array.isArray(x.page_config?.why_shop_cards)?x.page_config.why_shop_cards:[];return{id:x.id,name:x.name,plan:x.plan,cards,custom_count:cards.filter((c:any)=>c.id!=='location').length,custom_limit:['pro','premium'].includes(x.plan)?6:1}})})}
if(s==='users'){const[ps,ss]=await Promise.all([a.from('profiles').select('*').order('created_at',{ascending:false}),shops(a)]);if(ps.error)throw ps.error;const m=new Map(ss.map((x:any)=>[x.owner_id,x])),em=await emails(a,(ps.data||[]).map((x:any)=>x.id));return res.json({users:(ps.data||[]).map((x:any)=>{const q=m.get(x.id);return{...x,email:em.get(x.id)||'',shop_name:q?.name||'',plan:q?.plan||'free',shop_active:!!q?.is_active,last_activity:q?.updated_at||x.updated_at}})})}
if(s==='audit'){const l=await a.from('admin_audit_logs').select('*').order('created_at',{ascending:false}).limit(300);if(l.error)throw l.error;return res.json({logs:l.data||[]})}
return res.status(404).json({error:'Unknown section'})
}catch(e){return res.status(500).json({error:e instanceof Error?e.message:'Admin data query failed'})}}
