import React from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, Bell, CheckCircle2, CircleDollarSign, Clock3, LogOut, Menu, Package, Search, ShieldCheck, Store, Users, X } from 'lucide-react';
import type { SupabaseClient } from '@supabase/supabase-js';
import './styles.css';
import { createSupabaseClient } from './lib/supabase';
import { callAdminApi } from './lib/admin';

type Metric = { label:string; value:string; note:string; icon:React.ElementType };
type DashboardData = { metrics:{totalSellers:number; activeShops:number; products:number; premiumRevenue:number; premiumSellers:number; freeSellers:number; customerInterests:number; storefrontVisits:number}; payments:{id:string; amount:number; status:string; created_at:string}[]; legacyPayments:{id:string; amount:number; status:string; created_at:string}[]; latencyMs:number; requestId:string };
const nav = [['Dashboard', BarChart3], ['Sellers', Users], ['Shops', Store], ['Moderation', ShieldCheck], ['Payments', CircleDollarSign], ['Analytics', Activity]] as const;

type AuthProps = { client: SupabaseClient; onSuccess:()=>void };
function Signup({client,onSuccess}:AuthProps) {
 const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [confirm,setConfirm]=React.useState(''); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);try{const r=await fetch('/api/admin/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Unable to create admin account.');const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;onSuccess()}catch(e){setError(e instanceof Error?e.message:'Unable to create admin account.')}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-card"><div className="brand login-brand"><span className="mark">T</span><div><strong>ThreadZW</strong><small>MISSION CONTROL</small></div></div><p className="eyebrow">INITIAL ADMIN SETUP</p><h1>Create your admin account.</h1><p className="muted">This is a one-time setup. The first account becomes the ThreadZW Super Admin.</p><form onSubmit={submit}><label>Email<input autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="admin@threadzw.app"/></label><label>Password<input autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} required placeholder="At least 8 characters"/></label><label>Confirm password<input autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" minLength={8} required placeholder="Repeat your password"/></label>{error&&<div className="error"><AlertTriangle size={15}/>{error}</div>}<button className="primary full" disabled={busy}>{busy?'Creating admin…':'Create Super Admin'}</button></form><small className="security-note">After this account is created, public admin signup is permanently disabled.</small></div></div>
}
function Login({client,onSuccess}:AuthProps) {
 const [email,setEmail]=React.useState(''); const [password,setPassword]=React.useState(''); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await client.auth.signInWithPassword({email,password});if(error)setError(error.message);else onSuccess()}catch(e){setError(e instanceof Error?e.message:'Unable to sign in')}finally{setBusy(false)}}
 return <div className="login-page"><div className="login-card"><div className="brand login-brand"><span className="mark">T</span><div><strong>ThreadZW</strong><small>MISSION CONTROL</small></div></div><p className="eyebrow">SECURE ADMIN ACCESS</p><h1>Welcome back.</h1><p className="muted">Sign in with your approved ThreadZW admin account.</p><form onSubmit={submit}><label>Email<input autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="admin@threadzw.app"/></label><label>Password<input autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="••••••••"/></label>{error&&<div className="error"><AlertTriangle size={15}/>{error}</div>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><small className="security-note">Admin authorization is verified server-side.</small></div></div>
}
function ConfigurationError({message}:{message:string}) { return <div className="login-page"><div className="login-card"><div className="brand login-brand"><span className="mark">T</span><div><strong>ThreadZW</strong><small>MISSION CONTROL</small></div></div><p className="eyebrow">CONFIGURATION</p><h1>Mission Control can’t start.</h1><p className="muted">{message}</p><div className="error"><AlertTriangle size={15}/> Check the Vercel server environment variables and redeploy.</div></div></div> }

function Dashboard({onLogout}:{onLogout:()=>Promise<void>}) {
 const [data,setData]=React.useState<DashboardData|null>(null); const [loading,setLoading]=React.useState(true); const [error,setError]=React.useState(''); const [open,setOpen]=React.useState(false); const [section,setSection]=React.useState('Dashboard');
 async function load(){setLoading(true);setError('');try{setData(await callAdminApi<DashboardData>('/api/admin/dashboard'))}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}finally{setLoading(false)}}
 React.useEffect(()=>{load()},[]); const m=data?.metrics;
 const metrics:Metric[]=[{label:'Total sellers',value:m?m.totalSellers.toLocaleString():'—',note:'Registered accounts',icon:Users},{label:'Active shops',value:m?m.activeShops.toLocaleString():'—',note:'Currently active',icon:Store},{label:'Products',value:m?m.products.toLocaleString():'—',note:'Catalog inventory',icon:Package},{label:'Premium revenue',value:m?`$${m.premiumRevenue.toFixed(2)}`:'$—',note:'Current $9 lifetime only',icon:CircleDollarSign}];
 function select(label:string){setSection(label);setOpen(false)}
 if(section!=='Dashboard') return <Shell open={open} setOpen={setOpen} section={section} select={select} onLogout={onLogout}><div className="coming"><div className="coming-icon"><Activity/></div><p className="eyebrow">MISSION CONTROL</p><h1>{section}</h1><p className="muted">This module is wired into the navigation and will be connected to live production data next.</p><button className="secondary" onClick={()=>select('Dashboard')}>Back to dashboard</button></div></Shell>;
 return <Shell open={open} setOpen={setOpen} section={section} select={select} onLogout={onLogout}><section className="hero"><div><p className="eyebrow">OVERVIEW / OPERATIONS</p><h1>Good evening, Admin.</h1><p className="muted">Live platform intelligence from ThreadZW.</p></div><button className="primary" onClick={load}><ArrowUpRight size={16}/> Refresh data</button></section>{error&&<div className="error banner"><AlertTriangle size={16}/><span>{error}</span><button onClick={load}>Retry</button></div>}<section className="metrics">{metrics.map(x=>{const I=x.icon;return <article className="metric" key={x.label}><div className="metric-head"><span>{x.label}</span><I size={17}/></div><strong>{loading?'…':x.value}</strong><small>{x.note}</small></article>})}</section><section className="secondary-metrics"><div><span>Premium sellers</span><strong>{loading?'—':m?.premiumSellers.toLocaleString()}</strong></div><div><span>Free sellers</span><strong>{loading?'—':m?.freeSellers.toLocaleString()}</strong></div><div><span>Customer interests</span><strong>{loading?'—':m?.customerInterests.toLocaleString()}</strong><small>WhatsApp clicks</small></div><div><span>Storefront visits</span><strong>{loading?'—':m?.storefrontVisits.toLocaleString()}</strong></div></section><section className="grid"><article className="panel large"><div className="panel-head"><div><p className="eyebrow">PLATFORM PULSE</p><h2>Recent Premium payments</h2></div><span className="pill"><span className="dot"/> $9 lifetime</span></div>{loading?<div className="empty"><Clock3 size={25}/><span>Loading payment activity…</span></div>:data?.payments.length?<div className="activity-list">{data.payments.slice(0,6).map(p=><div className="activity-row" key={p.id}><div className="activity-icon"><CircleDollarSign size={16}/></div><div><strong>${Number(p.amount).toFixed(2)} Premium</strong><span>{new Date(p.created_at).toLocaleString()}</span></div><b className="status success">{p.status}</b></div>)}</div>:<div className="empty"><CheckCircle2 size={30}/><strong>No current Premium payments</strong><span>Payments will appear here as they are received.</span></div>}</article><article className="panel"><div className="panel-head"><div><p className="eyebrow">SYSTEM</p><h2>Operational health</h2></div><span className="pill"><span className="dot"/> Connected</span></div><div className="health-list"><div><span>Supabase API</span><b className="status success">Healthy</b></div><div><span>Admin API</span><b className="status success">{data?`${data.latencyMs}ms`:'Checking'}</b></div><div><span>Legacy payments</span><b>{data?.legacyPayments.length??'—'} records</b></div><div><span>Request ID</span><code>{data?.requestId?.slice(0,18)??'—'}</code></div></div></article></section></Shell>
}
function Shell({children,open,setOpen,section,select,onLogout}:{children:React.ReactNode;open:boolean;setOpen:(v:boolean)=>void;section:string;select:(v:string)=>void;onLogout:()=>Promise<void>}){return <div className="app"><header className="topbar"><button className="icon mobile" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button><div className="brand"><span className="mark">T</span><div><strong>ThreadZW</strong><small>MISSION CONTROL</small></div></div><div className="top-actions"><button className="search"><Search size={17}/><span>Search</span><kbd>⌘ K</kbd></button><button className="icon" aria-label="Notifications"><Bell size={18}/></button><button className="avatar" onClick={onLogout} title="Sign out">A</button></div></header><div className="layout"><aside className={open?'sidebar open':'sidebar'}><nav>{nav.map(([label,Icon])=><button className={section===label?'nav active':'nav'} key={label} onClick={()=>select(label)}><Icon size={18}/>{label}</button>)}</nav><div className="side-bottom"><button className="signout" onClick={onLogout}><LogOut size={15}/> Sign out</button><div className="health"><span className="dot"/>Systems nominal</div><small>ThreadZW Admin v0.2</small></div></aside><main><div className="mobile-overlay" onClick={()=>setOpen(false)}></div>{children}</main></div></div>}

function App(){
 const [client,setClient]=React.useState<SupabaseClient|null>(null); const [boot,setBoot]=React.useState<'loading'|'ready'|'error'>('loading'); const [session,setSession]=React.useState<any>(null); const [checking,setChecking]=React.useState(true); const [bootstrapAvailable,setBootstrapAvailable]=React.useState<boolean|null>(null); const [bootstrapError,setBootstrapError]=React.useState('');
 React.useEffect(()=>{let alive=true;(async()=>{try{const r=await fetch('/api/admin/config');const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Unable to load Supabase configuration.');const c=createSupabaseClient(body.url,body.anonKey);if(!alive)return;setClient(c);const [{data},b]=await Promise.all([c.auth.getSession(),fetch('/api/admin/bootstrap')]);const bootstrapBody=await b.json().catch(()=>({}));if(!b.ok)throw new Error(bootstrapBody.error||'Unable to reach admin setup service.');if(!alive)return;setSession(data.session);setBootstrapAvailable(Boolean(bootstrapBody.available));const {data:{subscription}}=c.auth.onAuthStateChange((_event,s)=>setSession(s));setBoot('ready');setChecking(false);return()=>subscription.unsubscribe()}catch(e){if(alive){setBootstrapError(e instanceof Error?e.message:'Unable to initialize Mission Control');setBoot('error');setChecking(false)}}})();return()=>{alive=false}},[]);
 if(boot==='loading')return <div className="loading-screen">Loading Mission Control…</div>; if(boot==='error'||!client)return <ConfigurationError message={bootstrapError||'Unable to initialize the admin application.'}/>; if(checking||bootstrapAvailable===null)return <div className="loading-screen">Loading Mission Control…</div>; if(!session)return bootstrapAvailable?<Signup client={client} onSuccess={()=>client.auth.getSession().then(({data})=>setSession(data.session))}/>:<Login client={client} onSuccess={()=>client.auth.getSession().then(({data})=>setSession(data.session))}/>; return <Dashboard onLogout={async()=>{await client.auth.signOut();setSession(null)}}/>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
